/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fltbhsapkxzemsncbtwj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsdGJoc2Fwa3h6ZW1zbmNidHdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODkzODEsImV4cCI6MjA3MTM2NTM4MX0.ldy4-IUt1clF0LmnOcH-dJIWosxwWM8kXeUQeurLRC8"